#!/usr/bin/env python3
"""Validate exported n8n workflow JSON files.

Checks:
- All 7 expected files present
- JSON parseable
- Required fields: name, nodes, connections
- Expected webhook trigger paths present
- No leaked secrets or credentials
- No bogus credential placeholder IDs
- No hardcoded ngrok or localhost domains (warn only for localhost)
- No dangerous implicit $json.body.X after non-webhook nodes (heuristic)
- Global error handler workflow exists
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / "workflows"

EXPECTED_FILES = {
    "01_lead_capture.json",
    "02_ai_qualification.json",
    "03_hot_lead_alert.json",
    "04_follow_up.json",
    "05_appointment_booking.json",
    "06_meeting_reminder.json",
    "99_global_error_handler.json",
}

# Webhook trigger paths expected in specific files
WEBHOOK_PATHS = {
    "01_lead_capture.json": "lead-created",
    "02_ai_qualification.json": "qualification-updated",
    "03_hot_lead_alert.json": "hot-lead-alert",
    "05_appointment_booking.json": "appointment-created",
}

# Patterns that indicate a leaked secret
SECRET_PATTERNS = [
    re.compile(r'sk-[a-zA-Z0-9]{10,}'),
    re.compile(r'BEGIN PRIVATE KEY'),
    re.compile(r'BEGIN RSA PRIVATE KEY'),
    re.compile(r'"password"\s*:\s*"[^"]{4,}"', re.I),
    re.compile(r'INTERNAL_API_KEY["\s]*:\s*"[^"]{4,}"'),
    re.compile(r'SMTP_PASSWORD["\s]*:\s*"[^"]{4,}"', re.I),
    re.compile(r'GOOGLE_CLIENT_SECRET["\s]*:\s*"[^"]{4,}"', re.I),
    re.compile(r'OPENAI_API_KEY["\s]*:\s*"[^"]{4,}"', re.I),
]

# Bogus placeholder credential IDs generated by code (not real n8n IDs)
BOGUS_CRED_PATTERNS = [
    re.compile(r'"id"\s*:\s*"CONFIGURE_[A-Z_]+"'),
    re.compile(r'"id"\s*:\s*"PLACEHOLDER_'),
    re.compile(r'"id"\s*:\s*"FAKE_'),
]

# Hardcoded external URL patterns (error)
HARDCODED_NGROK_PATTERN = re.compile(r'https?://[a-z0-9-]+\.ngrok[-.]', re.I)

# Heuristic: $json.body.X in HTTP Request nodes (dangerous after Register Execution)
# We warn when we see `$json.body.leadId`, `$json.body.eventId`, etc.
DANGEROUS_JINJA = re.compile(r'\$json\.body\.(leadId|eventId|appointmentId|correlationId|payload)')


def check_file(path: Path) -> list[str]:
    errors: list[str] = []
    warnings: list[str] = []
    blob = path.read_text(encoding="utf-8")
    try:
        data = json.loads(blob)
    except json.JSONDecodeError as e:
        return [f"{path.name}: JSON parse error: {e}"]

    if not data.get("name"):
        errors.append(f"{path.name}: missing 'name'")
    if not data.get("nodes"):
        errors.append(f"{path.name}: missing 'nodes'")
    if not data.get("connections"):
        errors.append(f"{path.name}: missing 'connections'")

    # Check required webhook path
    if path.name in WEBHOOK_PATHS:
        expected_path = WEBHOOK_PATHS[path.name]
        if expected_path not in blob:
            errors.append(f"{path.name}: missing webhook path '{expected_path}'")

    # Secret leakage
    for pat in SECRET_PATTERNS:
        if pat.search(blob):
            errors.append(f"{path.name}: possible secret/credential leaked (pattern: {pat.pattern[:40]})")

    # Bogus credential placeholder IDs
    for pat in BOGUS_CRED_PATTERNS:
        if pat.search(blob):
            errors.append(
                f"{path.name}: bogus credential ID detected — remove placeholder and configure real credential"
            )

    # Hardcoded ngrok domain
    if HARDCODED_NGROK_PATTERN.search(blob):
        errors.append(f"{path.name}: hardcoded ngrok URL — use $env.AI_SALES_BACKEND_URL or WEBHOOK_URL variable instead")

    # Heuristic: $json.body.X after non-webhook context
    matches = DANGEROUS_JINJA.findall(blob)
    if matches:
        fields = ", ".join(sorted(set(matches)))
        warnings.append(
            f"{path.name}: WARN — '$json.body.{{{fields}}}' detected. "
            "After HTTP Request nodes $json is the response, not the webhook body. "
            "Use explicit node reference: $('NodeName').item.json.body.field"
        )

    # Check for global error handler in node list
    if path.name == "99_global_error_handler.json":
        node_types = [n.get("type") for n in data.get("nodes", [])]
        if "n8n-nodes-base.errorTrigger" not in node_types:
            errors.append(f"{path.name}: missing errorTrigger node")

    return errors + warnings


def main() -> int:
    all_errors: list[str] = []
    all_warnings: list[str] = []

    if not WORKFLOWS.exists():
        print(f"ERROR: workflows directory not found: {WORKFLOWS}")
        return 1

    found_files = {p.name for p in WORKFLOWS.glob("*.json")}
    missing = EXPECTED_FILES - found_files
    for f in sorted(missing):
        all_errors.append(f"MISSING workflow file: {f}")

    for path in sorted(WORKFLOWS.glob("*.json")):
        results = check_file(path)
        for r in results:
            if r.startswith(path.name + ": WARN"):
                all_warnings.append(r)
            else:
                all_errors.append(r)

    # Summary
    if all_warnings:
        print("\nWARNINGS:")
        for w in all_warnings:
            print(f"  ⚠  {w}")

    if all_errors:
        print("\nVALIDATION FAILED")
        for e in all_errors:
            print(f"  ✗ {e}")
        return 1

    print(f"\nOK — all {len(found_files)} workflow JSON files validated")
    if all_warnings:
        print(f"     {len(all_warnings)} warning(s) above (non-blocking)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
