import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BarChart3,
  Bell,
  Boxes,
  Bot,
  CalendarDays,
  CalendarPlus,
  CheckCircle2,
  Database,
  Download,
  ExternalLink,
  Filter,
  Flame,
  Gauge,
  GitBranch,
  LayoutDashboard,
  ListChecks,
  Mail,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Network,
  Pencil,
  Phone,
  Plug,
  Plus,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Snowflake,
  Thermometer,
  Trash2,
  UserCheck,
  Users,
  UsersRound,
  Workflow,
  XCircle,
  type LucideIcon,
} from "lucide-react";

/** Canonical Lucide icons for product surfaces. */
export const ICONS = {
  dashboard: LayoutDashboard,
  leads: Users,
  pipeline: GitBranch,
  conversations: MessageSquare,
  appointments: CalendarDays,
  tasks: ListChecks,
  automations: Workflow,
  analytics: BarChart3,
  team: UsersRound,
  notifications: Bell,
  audit: ScrollText,
  integrations: Plug,
  settings: Settings,
  assistant: Bot,
  qualification: UserCheck,
  scoring: Gauge,
  security: ShieldCheck,
  email: Mail,
  success: CheckCircle2,
  warning: AlertTriangle,
  error: XCircle,
  info: AlertCircle,
  arrow: ArrowRight,
  external: ExternalLink,
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  export: Download,
  book: CalendarPlus,
  send: Send,
  filter: Filter,
  search: Search,
  hot: Flame,
  warm: Thermometer,
  cold: Snowflake,
  shieldAlert: ShieldAlert,
  denied: XCircle,
} as const;

export type AppIconName = keyof typeof ICONS;

export const INTEGRATION_ICONS: Record<string, LucideIcon> = {
  n8n: Workflow,
  calendar: CalendarDays,
  mail: Mail,
  hubspot: Network,
  slack: MessagesSquare,
  openai: Bot,
  odoo: Boxes,
  airtable: Database,
  teams: Users,
  whatsapp: MessageCircle,
  twilio: Phone,
  outlook: CalendarDays,
};

export const ICON_SIZE = {
  xs: 14,
  sm: 16,
  md: 18,
  lg: 20,
  xl: 24,
  hero: 28,
} as const;

export type IconSizeToken = keyof typeof ICON_SIZE;
